name: Doxygen Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo and submodules (in case doxygen-dark-theme is a submodule)
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Debug step to verify html_header.html is present
      - name: Debug: List workspace files
        run: |
          echo "Current dir: $(pwd)"
          ls -l docs/doxygen-dark-theme
          ls -l docs/doxygen-dark-theme/html_header.html

      # Run Doxygen
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./docs/Doxyfile"
          working-directory: "."

      # Deploy the generated documentation to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html

